name: Build and Auto-increment Version

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Auto-increment version number
        run: |
          VERSION=$(npm version patch)
          echo "New version: $VERSION"

      - name: Commit version number
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push https://${{ github.token }}@github.com/${{ github.repository }}.git HEAD:main
